// Stability AI API for line art generation
const STABILITY_API_KEY = process.env.STABILITY_API_KEY;

export async function generateLineArtWithStability(imageBuffer: Buffer): Promise<Buffer> {
  if (!STABILITY_API_KEY) {
    throw new Error("STABILITY_API_KEY not configured");
  }

  try {
    // Convert image to base64
    const base64Image = imageBuffer.toString('base64');

    // Use Stability AI's image-to-image with line art prompt
    const response = await fetch("https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/image-to-image", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${STABILITY_API_KEY}`,
        "Content-Type": "application/json",
        "Accept": "application/json"
      },
      body: JSON.stringify({
        init_image: base64Image,
        init_image_mode: "IMAGE_TO_IMAGE",
        image_strength: 0.35,
        steps: 30,
        seed: 0,
        cfg_scale: 7,
        samples: 1,
        text_prompts: [
          {
            text: "clean line art drawing of a dog's face, black lines on white background, minimalist, detailed facial features, professional illustration style",
            weight: 1
          },
          {
            text: "photorealistic, color, shading, background, noise, blur",
            weight: -1
          }
        ]
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Stability API error: ${response.status} - ${errorText}`);
    }

    const result = await response.json();
    
    if (result.artifacts && result.artifacts.length > 0) {
      const imageData = result.artifacts[0].base64;
      return Buffer.from(imageData, 'base64');
    }

    throw new Error("No image generated by Stability AI");
  } catch (error) {
    console.error("Stability AI error:", error);
    throw error;
  }
}

// Alternative: Use Stability's text-to-image with better prompts
export async function generateLineArtTextToImage(dogDescription: string): Promise<Buffer> {
  if (!STABILITY_API_KEY) {
    throw new Error("STABILITY_API_KEY not configured");
  }

  try {
    const response = await fetch("https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${STABILITY_API_KEY}`,
        "Content-Type": "application/json",
        "Accept": "application/json"
      },
      body: JSON.stringify({
        text_prompts: [
          {
            text: `clean line art drawing of ${dogDescription}, black lines on white background, minimalist style, detailed facial features, professional illustration, vector art style`,
            weight: 1
          },
          {
            text: "photorealistic, color, shading, background, noise, blur, painting, watercolor",
            weight: -1
          }
        ],
        cfg_scale: 7,
        height: 1024,
        width: 1024,
        samples: 1,
        steps: 30,
        seed: 0
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Stability API error: ${response.status} - ${errorText}`);
    }

    const result = await response.json();
    
    if (result.artifacts && result.artifacts.length > 0) {
      const imageData = result.artifacts[0].base64;
      return Buffer.from(imageData, 'base64');
    }

    throw new Error("No image generated by Stability AI");
  } catch (error) {
    console.error("Stability AI text-to-image error:", error);
    throw error;
  }
}
