[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "dogfaceart2"
