# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "424ce26e387d6af56b444085874d6416"
name = "dogfaceart3"
handle = "dogfaceart3"
application_url = "https://dogfaceart2.onrender.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_orders,read_products,write_files,write_orders,write_products"

[auth]
redirect_urls = [ "https://dogfaceart2.onrender.com/auth/callback" ]

[pos]
embedded = false
